### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Hebgbs** [timstableford/chatpad-linux#1]
Refuses to compile with `Failed at the @serialport/bindings@2.0.2 install script.`

npm 6.14.17

**Comment by timstableford** [comment]
I've uploaded a new node-chatpad library that updates the serialport library version and bumped it in this project. So hopefully a pull and an npm i should do it for you. Let me know

**Comment by Hebgbs** [comment]
`Failed at the ioctl@1.0.1 install script.`

Am I missing something? What are the deps for this I need to have installed in Arch?

I tried `npm i` only to be greeted with that error after the pull.

**Comment by timstableford** [comment]
The version of node-sass doesn't support the latest Node as far as I can gather. Try doing a `npm install node-sass@latest --save --force` before the `npm i`

**Comment by Hebgbs** [comment]
Success.
